# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

target 'Proverbs' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'ReachabilitySwift'
  pod 'RealmSwift'
  pod 'GhostTypewriter'
  pod 'SwiftHEXColors'
  pod 'SwiftyStoreKit'
  pod 'NVActivityIndicatorView'
  pod 'MGSwipeTableCell'
  pod 'DateToolsSwift'
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Performance'
  pod 'Firebase/AdMob'
  pod 'Firebase/Firestore'

  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'TwitterKit'
  pod 'GoogleSignIn'
  
  pod 'Fabric'
  pod 'Crashlytics'

end
